// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcavpbucgteohoabcxwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjYXZwYnVjZ3Rlb2hvYWJjeHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTcyNDQsImV4cCI6MjA1NTUzMzI0NH0.3eE3w-zn6WizBeZZrXRDilI8wvHJUtoEyqSy0xy3ITo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);